--DDL - CRIAR BANCO E TABELAS
--CRIAR UM BANCO
CREATE DATABASE Exercicio_1_1;

--USAR O BANCO CRIADO

USE Exercicio_1_1;

--CRIAR TABELAS
CREATE TABLE Pessoa
(
	IdPessoa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	CNH VARCHAR(11) NOT NULL UNIQUE
)

CREATE TABLE Telefone
(
	IdTelefone INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	Numero VARCHAR(15) NOT NULL UNIQUE
)

CREATE TABLE Email
(
	IdEmail INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa),
	Endereco VARCHAR(30) NOT NULL UNIQUE
)

DROP TABLE Pessoa;

SELECT * FROM Pessoa;
SELECT * FROM Telefone;
SELECT * FROM Email;