--DDL CRIAR BANCO E TABELAS

CREATE DATABASE O_EXERCICIO_1_4
USE O_EXERCICIO_1_4

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Estilo
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Tipo VARCHAR(20) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	TipoUsuario VARCHAR(3),
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(20) NOT NULL,
	Senha VARCHAR(8) NOT NULL
)



CREATE TABLE Artistas 
(
	IdArtistas INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Album
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtistas INT FOREIGN KEY REFERENCES Artistas(IdArtistas),
	Titulo VARCHAR(20) NOT NULL UNIQUE,
	Localização VARCHAR(25) NOT NULL,
	EstaAtivo VARCHAR(3) NOT NULL,
	DataLancamento DATE NOT NULL,
	QuantidadeMinutos INT NOT NULL
)



CREATE TABLE AlbumEstilo
(
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo)
)


SELECT * FROM Empresa;
SELECT * FROM Estilo;
SELECT * FROM Usuario;
SELECT * FROM Artistas;
SELECT * FROM Album;
SELECT * FROM AlbumEstilo;