--CRIAR BANCO DE DADOS
CREATE DATABASE Exercicio_1_2;

--USAR O BANCO DE DADOS CRIADO

USE Exercicio_1_2;

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)


CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Tipo VARCHAR(25) NOT NULL
)

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE
)

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

--------------------------------
--COM CHAVE ESTRANGEIRA

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	Placa VARCHAR(7)
)

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	Protocolo VARCHAR(15) NOT NULL UNIQUE
)

SELECT * FROM Empresa;
SELECT * FROM Modelo;
SELECT * FROM Cliente;
SELECT * FROM Marca;
SELECT * FROM Veiculo;
SELECT * FROM Aluguel;